Ruta2_EntradaSur_BosqueVerde_MapScripts::
	.byte 0

Ruta2_EntradaSur_BosqueVerde_EventScript_Mujer1::
	msgbox Ruta2_EntradaSur_BosqueVerde_Text_Mujer1, MSGBOX_NPC
	end

Ruta2_EntradaSur_BosqueVerde_EventScript_Mujer2::
	msgbox Ruta2_EntradaSur_BosqueVerde_Text_Mujer2, MSGBOX_NPC
	end

Ruta2_EntradaSur_BosqueVerde_Text_Mujer1::
    .string "{COLOR RED}¿Piensas ir al Bosque Verde?\p"
    .string "¡Ten cuidado!\n"
    .string "¡Es un auténtico laberinto!$"

Ruta2_EntradaSur_BosqueVerde_Text_Mujer2::
    .string "{COLOR RED}¡Puede que Rattata sea pequeño,\n"
    .string "pero su mordisco es muy potente!\p"
    .string "¿Tienes alguno?$"