Ruta2_EntradaNorte_BosqueVerde_MapScripts::
	.byte 0

Ruta2_EntradaNorte_BosqueVerde_EventScript_Joven::
	msgbox Ruta2_EntradaNorte_BosqueVerde_Text_Joven, MSGBOX_NPC
	end

Ruta2_EntradaNorte_BosqueVerde_EventScript_Anciano::
	msgbox Ruta2_EntradaNorte_BosqueVerde_Text_Anciano, MSGBOX_NPC
	end

Ruta2_EntradaNorte_BosqueVerde_EventScript_ChicaCool::
	msgbox Ruta2_EntradaNorte_BosqueVerde_Text_EntrenadoraCool, MSGBOX_NPC
	end

Ruta2_EntradaNorte_BosqueVerde_Text_EntrenadoraCool::
    .string "{COLOR RED}En este lugar no hay nada que\n"
    .string "pueda interesar a una Entrenadora\l"
    .string "Guay como yo.\p"
    .string "Salvo esas leyendas que dicen\n"
    .string "de la existencia de un\l"
    .string "Pinsir salvaje…$"

Ruta2_EntradaNorte_BosqueVerde_Text_Joven::
    .string "{COLOR BLUE}Hay muchos Pokémon que solo viven\n"
    .string "en bosques o cuevas.\p"
    .string "Necesitarás estar atento y ser\n"
    .string "constante si quieres tenerlos a\l"
    .string "todos.$"

Ruta2_EntradaNorte_BosqueVerde_Text_Anciano::
    .string "{COLOR BLUE}¡El eterno Bosque Verde!\n"
    .string "¡Ahhhh!\p"
    .string "¡Ni siquiera este lugar soportará\n"
    .string "el paso del tiempo!$"

